feat: add custom api data to plan
ixhbinphoenix/bne pull request #14
Opened 2023-03-23 20:19 UTC by Sxyntheon

The client can now make reuqeust to TheBackend server infrastucture to retrieve personalized data from Untis. This data is also fed into the plan to get displayed

2023-03-25 14:01 UTC, ixhbinphoenix requested changes

2023-03-25 14:01 UTC, ixhbinphoenix commented on frontend/src/components/plan-components/Stundenplan.tsx
> +                                if(lessons[k].substitution?.teacher != "---") {
This is always the case, since the API now returns null instead of ---

2023-03-26 11:02 UTC, Sxyntheon commented on frontend/src/api/main.ts
> +            return {
better?

2023-03-26 11:03 UTC, Sxyntheon commented on frontend/src/logs/testStudent.ts
>  export const testStudent: Array<TheScheduleObject>  = [
no

2023-03-26 11:08 UTC, ixhbinphoenix approved these changes
lgtm

2023-03-26 16:52 UTC, renkertm approved these changes
ok

2023-03-26 16:53 UTC, merged

2023-03-26 16:54 UTC, ixhbinphoenix commented
damn dude, fastest merge in the west