feat!(backend): Add databse, Untis API and own api routes
ixhbinphoenix/bne pull request #16
Opened 2023-03-24 20:51 UTC by ixhbinphoenix

Man this shouldn't be all in one PR wtf did we do

2023-03-24 21:18 UTC, Sxyntheon commented on backend/src/api_wrapper/untis_client.rs
holy ass bro how do you write these functions?!

2023-03-24 21:25 UTC, Sxyntheon approved these changes
What you guys did looks pretty good.

2023-03-26 16:36 UTC, renkertm commented on backend/src/api_wrapper/untis_client.rs
I dont know man...

2023-03-26 16:36 UTC, renkertm commented on backend/src/api_wrapper/untis_client.rs
My brain is fucked up sometimes

2023-03-26 16:37 UTC, renkertm requested changes
Come on first prototype this month

2023-03-26 16:38 UTC, renkertm commented
tf i didnt meant to request changes

2023-03-26 16:40 UTC, renkertm approved these changes
wasnt approve the last one? or am i just tired?

2023-03-26 16:40 UTC, merged